### ISSUE TITLE
Release builds for Ubuntu

### ISSUE THREAD

**Issue by icedevml** [mtrojnar/osslsigncode#250]
Hello! Thanks for publishing the tool. @mtrojnar Could you also include Ubuntu builds in the "Releases" section? I see that your CI is able to automatically build them as artifacts, but for some reason these are not included in the official releases. It would be a lot easier to be able to download the binary straight away instead of compiling it every time.

**Comment by mtrojnar** [comment]
So you're not happy with with the delay between publishing an upstream release and publishing an Ubuntu package, right?  Shouldn't you rather contact your Ubuntu package maintainer instead of reporting an issue to the upstream?

**Comment by icedevml** [comment]
I wasn't aware it's available as the `apt` package. Anyway, I see these packages contain older versions of `osslsigncode`. Would it be possible to just add the Ubuntu binaries straight in GitHub release 2.5? Your CI is anyway building them automatically.

**Comment by mtrojnar** [comment]
> Would it be possible to just add the Ubuntu binaries straight in GitHub release 2.5?

Yes, it would be possible, however I'm not going to do it.

**Comment by icedevml** [comment]
🤔

**Comment by icedevml** [comment]
Honestly I can't understand what is the problem here 🤔 I will switch to a different OSS tool since I don't want to use the stale release of the security app by fetching it from `apt`, and you are anyway making builds for three versions of Ubuntu but refusing to just upload them as the release asset without providing any reason.

**Comment by mtrojnar** [comment]
It looks like you're missing the point of using a distro (hint: maintaining package dependencies).  If your goal is to always have the latest software then Ubuntu looks like a suboptimal choice.

I use Ubuntu **for testing** because it's available on GitHub Actions. My goal is not to endorse it, and definitely not to explain to explain users why my builds are incompatible with whatever dependencies they may have installed on their version of Ubuntu.
