### ISSUE TITLE
MSI verification: data in unallocated sectors isn't checked

### ISSUE THREAD

**Issue by ebourg** [mtrojnar/osslsigncode#273]
If a signed MSI file is tempered by adding extra bytes at the end of the file in an area marked as unallocated in the FAT, the hash calculated doesn't change and osslsigncode still verifies it as valid, but the verification performed by signtool fails. Even if unallocated data has no impact on the hash it looks like Windows still checks it in some ways.

I'm attaching a sampe MSI file, it was signed then extended with 4096 white spaces at the end of the file.

[msi-with-unsigned-unallocated-data.zip](https://github.com/mtrojnar/osslsigncode/files/11649939/msi-with-unsigned-unallocated-data.zip)

**Comment by olszomal** [comment]
The signtool `Hash of file (sha256)` means `DigitalSignature` hash.

The MSI DigitalSignature hash only hashes file content stream data skipping unallocated streams and  `DigitalSignature` and `MsiDigitalSignatureEx` streams if exists.

```
The size of a compound file is determined by the index of the last non-free FAT array entry.
If the last FAT sector contains an entry FAT[N] != FREESECT (0xFFFFFFFF), 
the file size MUST be at least (N + 1) x (Sector Size) bytes in length.
```
The file size MAY be greater than the calculated value, because the sector with extra bytes added at the end of the file is marked in the FAT as FREESECT (unallocated).

WinVerifyTrust sanity check doesn't seem to match the documentation in this case, I think.
